services:

  drupal-app:
    image: drupal:11.0.5-php8.3-fpm-alpine3.19
    container_name: drupal-app
    volumes:
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    entrypoint: >
      sh -c "chown -R www-data:www-data /var/www/html/web && exec docker-php-entrypoint php-fpm"
    environment:
      - DRUPAL_DATABASE=drupal
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
      - DRUPAL_DB_HOST=drupal-db
    networks:
      - drupal-network

  drupal-db:
    image: mariadb:lts
    container_name: drupal-db
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - drupal-network

  nginx:
    image: nginx:mainline-alpine3.20-slim
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - drupal-app
    networks:
      - drupal-network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - drupal-db
    networks:
      - drupal-network

volumes:
  db-data:

networks:
  drupal-network:
    driver: bridge
